import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu 2.0 by Zetrov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = {
    method: "GET",
    url: `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`,
    params: {
      api_key: process.env.API_KEY,
    },
  };

  fetch(request)
    .then((data) => data)
    .catch((error) => console.log(error));

  // const request = await fetch(`https://api.themoviedb.org/3${
  //   requests[genre]?.url || requests.fetchTrending.url
  // }`, {
  //   headers: {
  //     "Access-Control-Allow-Origin": "*",
  //     "Content-Type": "text/plain",
  //   },
  // })
  // .then(function(res) {
  //   return res.json()
  // })

  return {
    props: {
      results: request.results,
    },
  };
}
